### ISSUE TITLE
5 functions fail their tests via check_functions

### ISSUE THREAD

**Issue by efiring** [TEOS-10/python-gsw#10]
check_functions.py is showing 5 functions with test output that doesn't match the check values:
- enthalpy_second_derivatives
- CT_freezing
- t_freezing
- brineSA_CT
- brineSA_t

I suspect that at least the last 4 of these were written based on an earlier Matlab version, and there have been considerable changes in the Matlab code for the freezing point calculations.  I don't know whether the problem with `enthalpy_second_derivatives` is also because of a change between Matlab versions, or something else.

**Comment by ocefpaf** [comment]
I am closing all issues in TEOS-10/python-gsw now that https://github.com/TEOS-10/GSW-Python is live.
