### ISSUE TITLE
Inland lat/lon returns NaN. Should use limnological equations

### ISSUE THREAD

**Issue by mankoff** [TEOS-10/python-gsw#15]
The following locations should return valid salinity assuming the data was collected in a lake.

```
gsw.SA_from_SP(0.1, -0.5, -70, 40) # PA coords
gsw.SA_from_SP(0.1, -0.5, -100, 40) # KS coords
```

From McDougall (2012):

> If the latitude and longitude are such as to place the observation well away from the ocean, a flag ‘in_ocean’ is set to zero as a warning, otherwise it is 1. This flag is only set when the observation is well and truly on dry land; often the warning flag is not set until one is several hundred kilometers inland from the coast. When the function detects that the observation is not from the ocean, Rδ is set equal to zero and gsw_Sstar_from_SP returns S\* = SR = (35.165 04 g kg−1/ 35) SP in accordance with Eqn. (3).

**Comment by ocefpaf** [comment]
Thank @mankoff I lost track of gsw.SA_from_SP, but I am sure we follow the Matlab code closely.  Maybe neither of them implement that.  Lets keep this issue open.  I am away from office but I will look into this as soon as I get back.

**Comment by richardsc** [comment]
Hi @ocefpaf and @mankoff!

Ken and I were talking about this issue offline, and I had a close look at both the Matlab and R implementations (note that the R package simply calls the C functions). As for Matlab, I used the following code to check the SA return values over the whole globe:

```matlab
clear all

lo = -180:180;
la = -86:90;
n = length(lo)*length(la);
[lon, lat] = meshgrid(lo, la);
llon = reshape(lon, 1, n);
llat = reshape(lat, 1, n);

SA = gsw_SA_from_SP(repmat(35, length(la), length(lo)), ...
                    repmat(100, length(la), length(lo)), ...
                    lon, lat);

pcolor(lon, lat, SA); shading flat
colormap(jet)
colorbar

print('-dpng', 'gsw_onland_matlab.png')
```
which produces:
![gsw_onland_matlab](https://cloud.githubusercontent.com/assets/233584/7838246/dc96313a-0459-11e5-8566-8b4c1eca553d.png)

The only place that Matlab (note that this is version 3.04 -- I haven't updated yet because I mostly just use the R package) doesn't return a value is when `lat < -86`. Note that the code above only tries lats down to -86 because `gsw_SA_from_SP` fails otherwise (rather than just return NaN).

**Comment by ocefpaf** [comment]
@richardsc Thanks!  I am away from my laptop until next week, but I will look at what `python-gsw` is doing as soon as possible.

My guess is that we might be masking everything that is in land.  Probably @efiring can say more about that.

**Comment by mankoff** [comment]
Python looks about the same as MATLAB. Perhaps this is just a mis-match between the documentation and the upstream 'official' code. Here is roughly what @richardsc did but in Python:

``python
lo = np.arange(-180,180)
la = np.arange(-90,90)
n = lo.size * la.size
[lon,lat] = np.meshgrid(lo,la)

import gsw
SA = gsw.SA_from_SP(np.zeros_like(lon)+35,
                    np.zeros_like(lon)+1,
                    lon, lat)


clf()
plt.contourf(lon,lat,SA)
colorbar()
savefig('gsw_onland_python.png')
```


![gsw_onland_python](https://cloud.githubusercontent.com/assets/145117/7838882/5d74bc74-045d-11e5-8490-fb1d6c5f8e1b.png)

**Comment by richardsc** [comment]
Nice! I edited to fix the code mark up and make the image work.

So, are the "land" points missing, or are they in the range between 0.010 and 0.012?

**Comment by ocefpaf** [comment]
That looks like the land is masked, maybe another colorbar will make that clearer.

I guess that the right question is: Should we make Rδ = 0, as per McDougall (2012), or should we discourage the use of `gsw.SA_from_SP` for lakes and such?

I need to go back to the deltaSA paper and the Millero 2008 to see if they mention anything about about this.

**Comment by mankoff** [comment]
Colorbar adjusted (to jet! :). Land is NaN.

**Comment by ocefpaf** [comment]
(Hurray to jet!  Who knew :stuck_out_tongue_winking_eye: )

**Comment by mankoff** [comment]
Some other related thoughts/comments on this issue:

1. We have MATLAB and Python code and figures above, which return NaNs on continents. The R code (not shown, which uses the official C code) does return data with continental coordinates. Presumably these are the limnological equations.

2. At the N. Pole, you get different values depending on your longitude.

**Comment by ocefpaf** [comment]
@mankoff Thanks!  I am wondering if this discussion should be expanded to @TEOS-10/owners instead of just @TEOS-10/team-python-gsw.

**Comment by richardsc** [comment]
To be clear, the Matlab version of GSW *does not* return NaNs on continents -- on when when lat < -86. From the Figure above the continental values of SA are all equal to the minimum value in the colormap.

**Comment by mankoff** [comment]
Oh sorry for that confusion Clark. It looked like that blue was < minimum. In this case, only python-gsw is behaving differently I think.

**Comment by ocefpaf** [comment]
Yes, `python-gsw` is masking as expected.  A least to me it does not make sense to call SA in places where the deltaSA is unavailable (Even if the docs says that it is setting it to zero making the values "correct", that is not SA!, unless I am missing something.)

I had a figure with the deltSA, but I cannot find it online now.  I will prepare another one once I get back.

**Comment by efiring** [comment]
There's a lot that needs to be done in python-gsw.  It's hard for me to imagine anything lower priority than making it return something "valid" in a lake.  What am I missing here?

**Comment by mankoff** [comment]
@efiring I'm not aware of what else needs to be done and/or priorities since it has appeared to work for me in all my other oceanographic use cases, and there are not many issues here on GitHub. If the other things that need to be done were here as tickets, I'd probably contribute a bit as I use the package.

**Comment by efiring** [comment]
@mankoff Excellent! Things needing to be done are not tickets because there is such an overwhelming amount that needs to be done. Substantial chunks are not implemented at all; and most of the rest needs to be checked against the newest Matlab release, to see what needs to be changed and what new things need to be added.  The Matlab version keeps getting changed in huge leaps, usually touching a large number of files in ways varying from trivial to major.  My understanding is that 3.05 should be the last such leap.  Our present code is based on a mixture of earlier versions, primarily 3.03 if I remember correctly.
There is also more work to be done in doc and docstring generation, and in testing.

**Comment by dankelley** [comment]
In case it's of any interest, I did some little tests (see [here](https://github.com/TEOS-10/GSW-R/issues/12)) to see how much difference the newly-updated polynomial makes. I admit that a single test is not too useful, but at least it gives a quick indication. My test indicates that the density change associated with the polynomial update is 1000X less than the uncertainty in density associated with the conductivity uncertainty for a typical CTD. Maybe my calculation is wrong, and maybe the point is that other base states will experience a larger effect from the formula change, but for now, recoding to the new polynomials might be of lower priority than coding the formulae for new variables.

**Comment by efiring** [comment]
@dankelley Thanks for doing the test and bringing it to our attention.  It's definitely of interest.

**Comment by PaulMBarker** [comment]
I am not sure by what is meant by "limnological equations", the TEOS-10 equations go down to salinities of 0 g/kg.

**Comment by PaulMBarker** [comment]
Does the python version of GSW return SA = 5.023577142857143 for SP = 5, p = 100, long = 40, lat = 50 ?

**Comment by efiring** [comment]
With #37, it does.

**Comment by mankoff** [comment]
@PaulMBarker It has been ~2 years and I'm not sure either at this point.

I have an email thread with from the date this ticket was opened with the author of "Limnological applications of the Thermodynamic Equation of Seawater 2010 (TEOS-10)" (see [doi:10.4319/lom.2012.10.853](http://dx.doi.org/10.4319/lom.2012.10.853))
