### ISSUE TITLE
Matlab GSW 3.05

### ISSUE THREAD

**Issue by ocefpaf** [TEOS-10/python-gsw#16]
Latest Matlab version is out.  Time to get back to work!

@paloczy  Do you have to some to volunteer for this project?  We are low on man power here!!!

**Comment by paloczy** [comment]
Sorry dude, can't do it now that my thesis defense is two months away.

**Comment by ocefpaf** [comment]
Se will still be needing help to months from now ;-)
Em 27/05/2015 12:43 PM, "André Palóczy" <notifications@github.com> escreveu:

**Comment by ocefpaf** [comment]
Closing this since we are going the c-wrapper route.
