### ISSUE TITLE
Consider enabling stickler-ci

### ISSUE THREAD

**Issue by ocefpaf** [TEOS-10/python-gsw#33]
This makes reviews much faster because `stickler` will comment on the PRs saving the human reviewer time. See https://stickler-ci.com/ for more information and https://github.com/python-visualization/folium/pull/602/files/5ec18b1c200500c098d5ebb9dd6fce35f91afeab for an example.

PS: I cannot enable it here. I guess that only @PaulMBarker has the TEOS-10 organization rights to do so.

**Comment by durack1** [comment]
@ocefpaf you could also add in [autopep8](https://pypi.python.org/pypi/autopep8/) as a standard step before submitting the PR.. Seems to work well in my testing..

**Comment by ocefpaf** [comment]
I use `autopep8` in other projects but `stickler` is better because it comments on the PR and let the reviewer and submitter deal with the coding standards in a higher, GitHub interface, level. (Check the example above.)

**Comment by efiring** [comment]
Wow!  That is *way* better than having to dredge the violations out of the Travis log!  Is there a catch?

**Comment by ocefpaf** [comment]
>  Is there a catch?

No catch. It requires a similar authorization as `.Travis-CI` and `AppVeyor`. (Adn it can lint many other languages too.)

**Comment by ocefpaf** [comment]
I am closing all issues in TEOS-10/python-gsw now that https://github.com/TEOS-10/GSW-Python is live.
