### ISSUE TITLE
Publish docs at TEOS-10/python-gsw

### ISSUE THREAD

**Issue by ocefpaf** [TEOS-10/python-gsw#36]
I am uploading the docs to https://ocefpaf.github.io/python-gsw/ because I do not have rights to add a deploy key here. @PaulMBarker could you expand our rights to this repo so we can do #33 and the docs?

**Comment by efiring** [comment]
@ocefpaf Paul made me an owner; now I just have to figure out what to do.

**Comment by ocefpaf** [comment]
OK. For stickler-ci I guess logging with GitHub and following adding the repo is enough:  the https://stickler-ci.com

For the docs the process is to install `doctr` (Python >=3.5 only) and issue `doctr configure`.
If everything goes well it will register the key automatically but you will need to replace the `secure` and `github_deploy_key.enc` in the repository too.

**Comment by ocefpaf** [comment]
I am closing all issue in TEOS-10/python-gsw now that https://github.com/TEOS-10/GSW-Python is live.
