### ISSUE TITLE
Release new version to PYPI

### ISSUE THREAD

**Issue by laliberte** [TEOS-10/python-gsw#38]
Would it be possible to submit a new version to PYPI? It would make continuous integration in other projects easier.

**Comment by ocefpaf** [comment]
We did had a few fixes lately but the latest version is still "updated."

@efiring are you OK with a minor release? Or do you want to wait for the c-wrapped version?

**Comment by efiring** [comment]
A minor release is OK with me, if you can find the time for it; it would do a bit of good and no harm that I can foresee.  Especially if there is a release, I would like to see one more change, though: somehow, take the unimplemented functions out of the namespace.  It could be by commenting them (the ones with a body of ``pass``), for example.  @castelao, do you want to do that?  I don't think it would take very long.

The "gswc" version is coming along well, with nearly everything wrapped that is ever likely to be wrapped.  That's 157 functions.  The few that remain are either very low priority, or probably more suitable for re-implementation in Python.   There is still a lot of work to be done, but I think there is little doubt that this is the direction we need to go.  I don't know how long it will take to get it "release-ready".  Right now I am looking at getting some testing set up, taking advantage of things from python-gsw.  Some reorganization may be needed.  I suppose I should also put in Py 2.7 support, but I'm tempted to leave that out.  The nightmare of building on Windows will need to be faced some time, by someone.

**Comment by laliberte** [comment]
Thanks @ocefpaf! Would it be possible to upload this latest version on PYPI?

**Comment by ocefpaf** [comment]
Already done. See https://pypi.org/project/gsw/

**Comment by laliberte** [comment]
Sorry @ocefpaf, I looked at the old PYPI website!

**Comment by ocefpaf** [comment]
Should be there too. But it may take a while for the site to process it.
