### ISSUE TITLE
geo_strf_steric_height

### ISSUE THREAD

**Issue by rpous** [TEOS-10/python-gsw#45]
Hi, I'm a Python User and a saw that this function isn't in the library yet.
Do you know if a traduction will be made ?
Thanks for you work

**Comment by ocefpaf** [comment]
Please see https://github.com/TEOS-10/GSW-Python/issues/68.

BTW. This repository is deprecated and I will archive it. The canonical source for Python gsw is in https://github.com/TEOS-10/GSW-Python now.
